http:
  routers:
    web-main:
      rule: "Host(`harun.dev`)"
      entryPoints:
        - web
      middlewares:
        - https-redirect
      service: web-blue
    web-main-secure:
      rule: "Host(`harun.dev`)"
      entryPoints:
        - websecure
      service: web-blue
      tls:
        certResolver: le
        domains:
          - main: "harun.dev"
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
  services:
    web-blue:
      loadBalancer:
        servers:
          - url: "http://nginx_blue:80"
        passHostHeader: true
    web-green:
      loadBalancer:
        servers:
          - url: "http://nginx_green:80"
        passHostHeader: true 