#!/bin/bash

set -e
set -o pipefail

# Get absolute path to script directory, regardless of where it's called from
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

# Usage:
#   ./deploy.sh [KEY=VALUE ...]
#   Example: ./deploy.sh APP_DEBUG=true FOO=bar
# Any key=value pairs passed as arguments will take highest priority in the generated .env file.
# The .env file is generated by merging, in order of precedence (lowest to highest):
#   1. .env.example (base)
#   2. deploy/.env.appprod (if exists)
#   3. deploy/.env.deploy (if exists)
#   4. Inline key=value arguments (provided at runtime)

# Define utility functions
fail() {
    echo "❌ ERROR: $1" >&2
    exit 1
}

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# Set up logging
LOG_DIR="$SCRIPT_DIR/log"
mkdir -p "$LOG_DIR"
# Archive previous deploy.log if it exists
if [ -f "$LOG_DIR/deploy.log" ]; then
  mv "$LOG_DIR/deploy.log" "$LOG_DIR/deploy-$(date '+%Y%m%d-%H%M%S').log"
fi
LOG_FILE="$LOG_DIR/deploy.log"
exec > >(tee -a "$LOG_FILE") 2>&1

# Load environment variables
if [ -f "$SCRIPT_DIR/.env.deploy" ]; then
  set -a
  source "$SCRIPT_DIR/.env.deploy"
  set +a
else
  fail "Missing .env.deploy file. Please create it based on .env.deploy.example."
fi

# Set defaults for optional variables
SSH_USER=${REMOTE_USER:-$SSH_USER}
SSH_HOST=${REMOTE_HOST:-$SSH_HOST}
SKIP_NPM_BUILD=${SKIP_NPM_BUILD:-true} # Skip npm build by default

# Validate required environment variables
if [ -z "$SSH_USER" ] || [ -z "$SSH_HOST" ] || [ -z "$APP_DIR" ] || [ -z "$GIT_REPO" ] || [ -z "$GIT_BRANCH" ]; then
    echo "Required environment variables:"
    echo "SSH_USER: $SSH_USER"
    echo "SSH_HOST: $SSH_HOST"
    echo "APP_DIR: $APP_DIR"
    echo "GIT_REPO: $GIT_REPO"
    echo "GIT_BRANCH: $GIT_BRANCH"
    fail "Missing required environment variables. Please check your .env.deploy file."
fi

# Set SSH key path - always in the script directory
SSH_KEY="$SCRIPT_DIR/portfolio-key.pem"

# Check if SSH key exists
if [ ! -f "$SSH_KEY" ]; then
    fail "SSH key not found at $SSH_KEY. Please place your private key there."
fi

# Fix SSH key permissions
chmod 600 "$SSH_KEY"

# Function to run a command on the remote server
ssh_run() {
    ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$SSH_USER@$SSH_HOST" "$@"
}

# Function to copy files to the remote server
scp_copy() {
    local source="$1"
    local dest="$2"
    scp -i "$SSH_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$source" "$SSH_USER@$SSH_HOST:$dest"
}

# Function to copy directories to the remote server
scp_dir_copy() {
    local source="$1"
    local dest="$2"
    scp -i "$SSH_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r "$source" "$SSH_USER@$SSH_HOST:$dest"
}

# Traefik-specific blue-green deployment functions
get_active_env() {
    local active_env=""
    active_env=$(ssh_run "docker ps --filter 'label=environment=blue' --format '{{.Names}}' | grep -c app-blue || echo 0")
    
    if [ "$active_env" -gt 0 ]; then
        echo "blue"
    else
        active_env=$(ssh_run "docker ps --filter 'label=environment=green' --format '{{.Names}}' | grep -c app-green || echo 0")
        if [ "$active_env" -gt 0 ]; then
            echo "green"
        else
            echo "blue"  # Default to blue if no environment is running
        fi
    fi
}

get_inactive_env() {
    local active_env="$1"
    if [ "$active_env" = "blue" ]; then
        echo "green"
    else
        echo "blue"
    fi
}

check_traefik_health() {
    local env="$1"
    local max_attempts=10
    local attempt=1
    local wait_time=5
    
    echo "Performing health check for $env environment..."
    
    while [ $attempt -le $max_attempts ]; do
        echo "Health check attempt $attempt of $max_attempts..."
        
        # Check if container is running
        local container_status
        container_status=$(ssh_run "docker ps --filter name=app-$env --format '{{.Status}}' | grep -c 'Up' || echo 0")
        
        if [ "$container_status" -ge "1" ]; then
            echo "Container for $env environment is running."
            
            # Check if app is responding through curl
            local http_status
            http_status=$(ssh_run "curl -s -o /dev/null -w '%{http_code}' http://localhost || echo 'failed'")
            
            if [ "$http_status" = "200" ] || [ "$http_status" = "204" ] || [ "$http_status" = "301" ] || [ "$http_status" = "302" ]; then
                echo "Health check passed: $env environment is responding with HTTP $http_status"
                return 0
            else
                echo "Health check failed: environment responded with HTTP $http_status"
            fi
        else
            echo "Container for $env environment is not running properly."
        fi
        
        attempt=$((attempt + 1))
        sleep $wait_time
    done
    
    echo "Health check failed after $max_attempts attempts."
    return 1
}

# Function to begin recording time
start_time=$(date +%s)
STEP_START_TIME=$start_time
STEP_NUM=0
STEP_TIMES=()

# Function to mark the beginning of a step
step() {
  STEP_NUM=$((STEP_NUM + 1))
  echo -e "\n=== STEP $STEP_NUM: $1 ==="
  STEP_START_TIME=$(date +%s)
}

# Function to mark the end of a step
end_step() {
  local end_time=$(date +%s)
  local duration=$((end_time - STEP_START_TIME))
  STEP_TIMES+=("$duration")
  echo "Step completed in $duration seconds."
}

# Function to print the total time
print_total_time() {
  local end_time=$(date +%s)
  local total_duration=$((end_time - start_time))
  echo -e "\n=== DEPLOYMENT COMPLETED IN $total_duration SECONDS ==="
  
  for i in "${!STEP_TIMES[@]}"; do
    local step_num=$((i + 1))
    echo "Step $step_num took ${STEP_TIMES[$i]} seconds"
  done
}

# Process additional key=value pairs from command line arguments
additional_env_pairs=()
for arg in "$@"; do
  if [[ $arg == *=* ]]; then
    additional_env_pairs+=("$arg")
  fi
done

# Parse the key-value pairs for APP_DEBUG
for pair in "${additional_env_pairs[@]}"; do
  key="${pair%%=*}"
  value="${pair#*=}"
  if [[ "$key" == "APP_DEBUG" ]]; then
    APP_DEBUG="$value"
  fi
done

# 1. Build assets locally
step "Building assets locally"
if [ -f "$REPO_ROOT/package.json" ]; then
  if [ "${SKIP_NPM_BUILD:-false}" != "true" ]; then
    echo "Building frontend assets..."
    
    # Check if npm is installed
    if ! command -v npm &> /dev/null; then
      fail "npm is required but not installed. Please install npm and try again."
    fi
    
    # Check if node_modules exists
    if [ ! -d "$REPO_ROOT/node_modules" ]; then
      echo "Installing npm dependencies..."
      cd "$REPO_ROOT" && npm install
    fi
    
    # Build assets
    echo "Running npm run build..."
    cd "$REPO_ROOT" && npm run build
    
    if [ $? -ne 0 ]; then
      fail "npm build failed. See error messages above."
    fi
  else
    echo "Skipping npm build (SKIP_NPM_BUILD is true)"
  fi
else
  echo "No package.json found, skipping asset build."
fi
end_step

# 2. Create build directory
step "Creating build directory"
BUILD_DIR="$SCRIPT_DIR/build"
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"
end_step

# 3. Generate .env file
step "Generating .env file"
ENV_FILE="$BUILD_DIR/.env"

# Start with a base .env file
BASE_ENV_FILE="$REPO_ROOT/.env.example"
if [ ! -f "$BASE_ENV_FILE" ]; then
  BASE_ENV_FILE="$REPO_ROOT/.env"
  if [ ! -f "$BASE_ENV_FILE" ]; then
    fail "No .env.example or .env file found in the repository root."
  fi
fi

# Copy the base .env file to the build directory
cp "$BASE_ENV_FILE" "$ENV_FILE"

# Apply .env.appprod if it exists
if [ -f "$SCRIPT_DIR/.env.appprod" ]; then
  echo "Applying .env.appprod..."
  while IFS= read -r line; do
    if [[ $line == \#* ]] || [[ -z $line ]]; then
      continue
    fi
    key=$(echo "$line" | cut -d= -f1)
    # Escape special characters in the key for use in sed
    escaped_key=$(echo "$key" | sed 's/[\/&]/\\&/g')
    # Check if the key exists in the .env file
    if grep -q "^$escaped_key=" "$ENV_FILE"; then
      # Replace the existing value
      sed -i '' "s/^$escaped_key=.*/$line/" "$ENV_FILE"
    else
      # Add the new key-value pair
      echo "$line" >> "$ENV_FILE"
    fi
  done < "$SCRIPT_DIR/.env.appprod"
fi

# Apply .env.deploy if it exists and the key is not in our exclusion list
if [ -f "$SCRIPT_DIR/.env.deploy" ]; then
  echo "Applying .env.deploy..."
  # Keys to exclude from .env.deploy
  exclude_keys=(
    "SSH_USER"
    "SSH_HOST"
    "APP_DIR"
    "GIT_REPO"
    "GIT_BRANCH"
    "SKIP_NPM_BUILD"
    "REMOTE_FILES"
    "CLOUDFLARE_API_TOKEN"
    "CLOUDFLARE_ZONE_ID"
    "CLOUDFLARE_ACCOUNT_ID"
    "CLOUDFLARE_EMAIL"
    "CLOUDFLARE_API_KEY"
    "AWS_ACCESS_KEY_ID"
    "AWS_SECRET_ACCESS_KEY"
    "AWS_REGION"
    "R2_BUCKET_NAME"
    "ARTIFACT_UPLOAD_KEY"
    "ARTIFACT_UPLOAD_SECRET"
    "REMOTE_USER"
    "REMOTE_HOST"
  )
  
  while IFS= read -r line; do
    if [[ $line == \#* ]] || [[ -z $line ]]; then
      continue
    fi
    key=$(echo "$line" | cut -d= -f1)
    
    # Skip if the key is in the exclusion list
    if [[ " ${exclude_keys[*]} " == *" $key "* ]]; then
      continue
    fi
    
    # Escape special characters in the key for use in sed
    escaped_key=$(echo "$key" | sed 's/[\/&]/\\&/g')
    # Check if the key exists in the .env file
    if grep -q "^$escaped_key=" "$ENV_FILE"; then
      # Replace the existing value
      sed -i '' "s/^$escaped_key=.*/$line/" "$ENV_FILE"
    else
      # Add the new key-value pair
      echo "$line" >> "$ENV_FILE"
    fi
  done < "$SCRIPT_DIR/.env.deploy"
fi

# Apply additional key=value pairs from command line arguments
if [ ${#additional_env_pairs[@]} -gt 0 ]; then
  echo "Applying command line arguments..."
  for pair in "${additional_env_pairs[@]}"; do
    key="${pair%%=*}"
    value="${pair#*=}"
    # Escape special characters in the key and value for use in sed
    escaped_key=$(echo "$key" | sed 's/[\/&]/\\&/g')
    escaped_value=$(echo "$value" | sed 's/[\/&]/\\&/g')
    # Check if the key exists in the .env file
    if grep -q "^$escaped_key=" "$ENV_FILE"; then
      # Replace the existing value
      sed -i '' "s/^$escaped_key=.*/$escaped_key=$escaped_value/" "$ENV_FILE"
    else
      # Add the new key-value pair
      echo "$key=$value" >> "$ENV_FILE"
    fi
  done
fi

echo ".env file generated at $ENV_FILE"
end_step

# Download and upload remote files
SCP_REMOTE_FILES=()
if [ ${#REMOTE_FILES[@]} -gt 0 ]; then
  step "Downloading and uploading remote files"
  for remote_file in "${REMOTE_FILES[@]}"; do
    IFS=':' read -r url destination <<< "$remote_file"
    filename=$(basename "$url")
    temp_file="/tmp/$filename"
    
    echo "Downloading $url to $temp_file..."
    curl -s -o "$temp_file" "$url"
    
    # If destination starts with '/', it's an absolute path, otherwise it's relative to APP_DIR
    if [[ "$destination" == /* ]]; then
      SCP_REMOTE_FILES+=("$temp_file:$destination")
    else
      SCP_REMOTE_FILES+=("$temp_file:$APP_DIR/$destination")
    fi
  done
fi

# 7. Generate deployment script for the server
step "Generating deployment script for server"
DEPLOY_SCRIPT="$BUILD_DIR/server-deploy.sh"
cat > "$DEPLOY_SCRIPT" << 'EOF'
#!/bin/bash

set -e
set -o pipefail

# Function to handle failures
fail() {
  echo "❌ ERROR: $1"
  exit 1
}

# Ensure the storage directory structure is correct
mkdir -p storage/app/public \
         storage/framework/cache/data \
         storage/framework/sessions \
         storage/framework/views \
         storage/logs \
         bootstrap/cache

# Fix permissions
chmod -R 755 storage bootstrap/cache

# Run composer dump-autoload to optimize autoloader
if command -v composer &> /dev/null; then
  composer dump-autoload --optimize
else
  echo "Composer not found, skipping autoload optimization."
fi

# Run Laravel-specific optimization commands if artisan exists
if [ -f "artisan" ]; then
  php artisan optimize:clear
  php artisan config:cache
  php artisan route:cache
  php artisan view:cache
else
  echo "Artisan not found, skipping Laravel optimizations."
fi

# Create storage link if it doesn't exist
if [ -f "artisan" ] && [ ! -L "public/storage" ]; then
  php artisan storage:link
fi

echo "Server-side deployment script completed successfully!"
EOF
chmod +x "$DEPLOY_SCRIPT"
end_step

# 4. Establish SSH connection
step "Establishing SSH connection"
echo "Checking SSH connection to $SSH_USER@$SSH_HOST..."
if ! ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=10 "$SSH_USER@$SSH_HOST" "echo 'SSH connection successful'"; then
  fail "Failed to establish SSH connection to $SSH_HOST. Please check your SSH credentials and server status."
fi
end_step

# 5. Check if directory exists, create if it doesn't
step "Checking and creating application directory"
ssh_run "mkdir -p $APP_DIR"
end_step

# 6. Clone or pull repository
step "Cloning or pulling repository"
REPO_EXISTS=$(ssh_run "if [ -d $APP_DIR/.git ]; then echo 'yes'; else echo 'no'; fi")
if [ "$REPO_EXISTS" = "yes" ]; then
  echo "Repository exists, pulling latest changes..."
  ssh_run "cd $APP_DIR && git fetch && git checkout $GIT_BRANCH && git pull origin $GIT_BRANCH"
else
  echo "Repository doesn't exist, cloning..."
  ssh_run "cd $(dirname "$APP_DIR") && git clone --branch $GIT_BRANCH $GIT_REPO $(basename "$APP_DIR")"
fi
end_step

# Transfer application files to the server
step "Transferring application files"
echo "Copying .env file to the server..."
scp_copy "$ENV_FILE" "$APP_DIR/.env"

echo "Copying deployment script to the server..."
scp_copy "$DEPLOY_SCRIPT" "$APP_DIR/deploy.sh"
ssh_run "chmod +x $APP_DIR/deploy.sh"

# Copy docker directory to the server
echo "Copying Docker configuration to the server..."
ssh_run "mkdir -p $APP_DIR/docker"
scp_dir_copy "$REPO_ROOT/docker/." "$APP_DIR/docker/"

# Upload remote files if any
if [ ${#SCP_REMOTE_FILES[@]} -gt 0 ]; then
  echo "Uploading remote files..."
  for remote_file in "${SCP_REMOTE_FILES[@]}"; do
    IFS=':' read -r source destination <<< "$remote_file"
    echo "Copying $source to $destination..."
    scp_copy "$source" "$destination"
  done
fi
end_step

# Deploy with Traefik
step "Deploying with Traefik"

# Get the current active environment
echo "Checking active environment..."
ACTIVE_ENV=$(get_active_env)
INACTIVE_ENV=$(get_inactive_env "$ACTIVE_ENV")
echo "Current active environment: $ACTIVE_ENV"
echo "Target deployment environment: $INACTIVE_ENV"

# Deploy docker-compose.yml with Traefik configuration
echo "Deploying with Traefik in blue-green deployment mode..."

# Start the inactive environment
echo "Starting $INACTIVE_ENV environment..."
ssh_run "cd $APP_DIR && docker-compose -f docker/docker-compose.yml up -d app-$INACTIVE_ENV db traefik"

# Run Laravel commands in the new container
echo "Running Laravel commands in the new container..."
ssh_run "docker exec app-$INACTIVE_ENV php artisan config:cache"
ssh_run "docker exec app-$INACTIVE_ENV php artisan route:cache"
ssh_run "docker exec app-$INACTIVE_ENV php artisan view:cache"

# Check health of the new environment
if check_traefik_health "$INACTIVE_ENV"; then
    echo "New $INACTIVE_ENV environment is healthy!"
    
    # Stop the old environment if it exists
    if [ "$ACTIVE_ENV" != "$INACTIVE_ENV" ]; then
        echo "Stopping old $ACTIVE_ENV environment..."
        ssh_run "cd $APP_DIR && docker-compose -f docker/docker-compose.yml stop app-$ACTIVE_ENV"
    fi
    
    echo "Deployment successful! Traffic is now routed to the $INACTIVE_ENV environment."
else
    echo "Health check failed for the new environment. Keeping the old environment active."
    echo "Check logs: ssh $SSH_USER@$SSH_HOST 'docker logs app-$INACTIVE_ENV'"
    fail "Deployment failed due to health check failure."
fi
end_step

# Final health check
step "Final Health Check"
HEALTH_CHECK_RESULT=$(ssh_run "curl -s -o /dev/null -w '%{http_code}' http://localhost || echo 'failed'")
if [[ "$HEALTH_CHECK_RESULT" =~ ^(200|204|301|302)$ ]]; then
  echo "✅ Health check passed! Application is running with status code $HEALTH_CHECK_RESULT."
else
  echo "❌ Health check failed with status $HEALTH_CHECK_RESULT! Application may not be running properly."
  echo "Check the logs on the server:"
  echo "  ssh $SSH_USER@$SSH_HOST 'docker logs \$(docker ps --filter \"name=app-$INACTIVE_ENV\" --format \"{{.Names}}\" | head -1)'"
fi
end_step

# 11. Purge CDN Cache (Cloudflare)
step "Purging CDN Cache (Cloudflare)"
if [ -z "$CLOUDFLARE_ZONE_ID" ] || [ -z "$CLOUDFLARE_API_TOKEN" ]; then
  echo "Skipping Cloudflare CDN purge - missing CLOUDFLARE_ZONE_ID or CLOUDFLARE_API_TOKEN"
  echo "To enable Cloudflare cache purging, add the following to your .env.deploy file:"
  echo "CLOUDFLARE_API_TOKEN=your_api_token"
  echo "CLOUDFLARE_ZONE_ID=your_zone_id"
else
  echo "Attempting to purge Cloudflare cache for zone ID $CLOUDFLARE_ZONE_ID"
  if [ -n "$CLOUDFLARE_API_TOKEN" ]; then
    echo "Using API Token authentication method..."
    RESULT=$(curl -s -X POST \
      "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
      -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
      -H "Content-Type: application/json" \
      --data '{"purge_everything":true}')

    # Parse JSON properly to check for success
    SUCCESS=$(echo "$RESULT" | grep -o '"success":[^,}]*' | cut -d ':' -f2 | tr -d ' ')
    if [[ "$SUCCESS" == "true" ]]; then
      echo "Cloudflare cache purged successfully!"
    else
      echo "Failed to purge Cloudflare cache. Response: $RESULT"
    fi
  elif [ -n "$CLOUDFLARE_EMAIL" ] && [ -n "$CLOUDFLARE_API_KEY" ]; then
    echo "Using API Key authentication method..."
    RESULT=$(curl -s -X POST \
      "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
      -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
      -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
      -H "Content-Type: application/json" \
      --data '{"purge_everything":true}')

    # Parse JSON properly to check for success
    SUCCESS=$(echo "$RESULT" | grep -o '"success":[^,}]*' | cut -d ':' -f2 | tr -d ' ')
    if [[ "$SUCCESS" == "true" ]]; then
      echo "Cloudflare cache purged successfully!"
    else
      echo "Failed to purge Cloudflare cache. Response: $RESULT"
    fi
  else
    echo "Missing Cloudflare authentication credentials. Please provide either API Token or Email + API Key."
  fi
fi
end_step

# Debugging functions for SSH if needed
debug_traefik() {
  echo "====== Debugging Traefik ======"
  ssh_run "docker ps | grep traefik || echo 'Traefik container not found!'"
  ssh_run "docker logs \$(docker ps --filter 'name=traefik' --format '{{.Names}}' | head -1) 2>&1 | tail -50"
  ssh_run "docker inspect \$(docker ps --filter 'name=traefik' --format '{{.Names}}' | head -1) | grep -A 10 'PortBindings'"
  
  echo "====== Checking app containers ======"
  ssh_run "docker ps | grep 'app-'"
  ssh_run "docker logs \$(docker ps --filter 'name=app-' --format '{{.Names}}' | head -1) 2>&1 | tail -50"
  
  echo "====== Checking basic connectivity ======"
  ssh_run "curl -I http://localhost 2>&1 || echo 'Failed to connect to localhost:80'"
  ssh_run "curl -I https://localhost 2>&1 || echo 'Failed to connect to localhost:443'"
}

# Print total time and summary
print_total_time