#!/bin/bash

set -e
set -o pipefail

# Get absolute path to script directory, regardless of where it's called from
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

# Usage:
#   ./deploy.sh [KEY=VALUE ...]
#   Example: ./deploy.sh APP_DEBUG=true FOO=bar
# Any key=value pairs passed as arguments will take highest priority in the generated .env file.
# The .env file is generated by merging, in order of precedence (lowest to highest):
#   1. .env.example (base)
#   2. deploy/.env.appprod (if exists)
#   3. deploy/.env.deploy (if exists)
#   4. Inline key=value arguments (provided at runtime)

# Define utility functions
fail() {
    echo "[ERROR] $1" >&2
    exit 1
}

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# Set up logging
LOG_DIR="$SCRIPT_DIR/log"
mkdir -p "$LOG_DIR"
# Archive previous deploy.log if it exists
if [ -f "$LOG_DIR/deploy.log" ]; then
  mv "$LOG_DIR/deploy.log" "$LOG_DIR/deploy-$(date '+%Y%m%d-%H%M%S').log"
fi
LOG_FILE="$LOG_DIR/deploy.log"
exec > >(tee -a "$LOG_FILE") 2>&1

# Load environment variables
if [ -f "$SCRIPT_DIR/.env.deploy" ]; then
  set -a
  source "$SCRIPT_DIR/.env.deploy"
  set +a
else
  fail "Missing .env.deploy file. Please create it based on .env.deploy.example."
fi

# Set defaults for optional variables
SSH_USER=${REMOTE_USER:-$SSH_USER}
SSH_HOST=${REMOTE_HOST:-$SSH_HOST}
SKIP_NPM_BUILD=${SKIP_NPM_BUILD:-true} # Skip npm build by default

# Validate required environment variables
if [ -z "$SSH_USER" ] || [ -z "$SSH_HOST" ] || [ -z "$APP_DIR" ] || [ -z "$GIT_REPO" ] || [ -z "$GIT_BRANCH" ]; then
    echo "Required environment variables:"
    echo "SSH_USER: $SSH_USER"
    echo "SSH_HOST: $SSH_HOST"
    echo "APP_DIR: $APP_DIR"
    echo "GIT_REPO: $GIT_REPO"
    echo "GIT_BRANCH: $GIT_BRANCH"
    fail "Missing required environment variables. Please check your .env.deploy file."
fi

# Set SSH key path - always in the script directory
SSH_KEY="$SCRIPT_DIR/portfolio-key.pem"

# Check if SSH key exists
if [ ! -f "$SSH_KEY" ]; then
  fail "SSH key file not found at $SSH_KEY."
fi

# Ensure SSH key has correct permissions
chmod 600 "$SSH_KEY"

# Parse command line arguments for additional environment variables
ADDITIONAL_ENV_VARS=()
for arg in "$@"; do
  if [[ $arg == *=* ]]; then
    ADDITIONAL_ENV_VARS+=("$arg")
  fi
done

# Function to execute SSH commands
execute_ssh() {
  ssh -i "$SSH_KEY" "$SSH_USER@$SSH_HOST" "$1"
}

# Function to start a deployment step
step() {
  STEP_NUM=$((STEP_NUM + 1))
  STEP_DESC="$1"
  STEP_START=$(date +%s)
  echo ""
  echo "++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+++   STEP $STEP_NUM: $STEP_DESC   +++"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++"
  echo ""
}

# Function to end a deployment step and print time taken
end_step() {
  STEP_END=$(date +%s)
  STEP_DURATION=$((STEP_END - STEP_START))
  if [ $STEP_DURATION -gt 5 ]; then
    echo "Step took $STEP_DURATION seconds."
    echo ""
  fi
}

# Function to print total deployment time
print_total_time() {
  DEPLOY_END=$(date +%s)
  DEPLOY_DURATION=$((DEPLOY_END - DEPLOY_START))
  MINUTES=$((DEPLOY_DURATION / 60))
  SECONDS=$((DEPLOY_DURATION % 60))
  
  echo ""
  echo "++++++++++++++++++++++++++++++++++++++++++++++++"
  echo "+++   DEPLOYMENT COMPLETED SUCCESSFULLY   +++"
  echo "++++++++++++++++++++++++++++++++++++++++++++++++"
  echo ""
  echo "Total deployment time: $MINUTES minutes and $SECONDS seconds"
  echo "Deployment log saved to: $LOG_FILE"
  echo ""
  echo "Your application is now live at: https://${DOMAIN:-$SSH_HOST}"
  echo ""
}

# Initialize step counter and start time
STEP_NUM=0
DEPLOY_START=$(date +%s)

# 1. Check if we can connect to the server
step "Checking SSH connection to server"
if ! ssh -i "$SSH_KEY" -o ConnectTimeout=10 -o BatchMode=yes -o StrictHostKeyChecking=accept-new "$SSH_USER@$SSH_HOST" "echo 'SSH connection successful'"; then
  fail "Cannot connect to server. Please check your SSH credentials and server status."
fi
end_step

# 2. Check if required tools are installed locally
step "Checking required tools"
for cmd in git rsync curl aws; do
  if ! command -v $cmd &> /dev/null; then
    fail "Required command '$cmd' not found. Please install it and try again."
  fi
done
end_step

# 3. Prepare local environment
step "Preparing local environment"
# Create a temporary directory for build artifacts
BUILD_DIR="$SCRIPT_DIR/build"
mkdir -p "$BUILD_DIR"

# Ensure we're in the repository root
cd "$REPO_ROOT"

# Check if the repository is clean
if [ -n "$(git status --porcelain)" ]; then
  echo "Warning: Git repository has uncommitted changes. These will not be deployed."
  echo "Consider committing your changes before deploying."
fi
end_step

# 4. Build assets locally if needed
step "Building assets locally"
if [ -f "$REPO_ROOT/package.json" ]; then
  if [ "${SKIP_NPM_BUILD:-false}" != "true" ]; then
    echo "Building frontend assets..."
    
    # Check if npm is installed
    if ! command -v npm &> /dev/null; then
      fail "npm is required but not installed. Please install npm and try again."
    fi
    
    # Install dependencies if node_modules doesn't exist or if forced
    if [ ! -d "$REPO_ROOT/node_modules" ] || [ "${FORCE_NPM_INSTALL:-false}" == "true" ]; then
      echo "Installing npm dependencies..."
      npm ci || npm install
    fi
    
    # Build assets
    npm run build
  else
    echo "Skipping npm build as SKIP_NPM_BUILD=true"
  fi
else
  echo "No package.json found, skipping asset build."
fi
end_step

# 5. Upload static assets to CDN if configured
step "Uploading static assets to CDN"
if [ -n "$R2_BUCKET_NAME" ] && [ -n "$R2_ACCESS_KEY_ID" ] && [ -n "$R2_SECRET_ACCESS_KEY" ] && [ -n "$R2_S3_ENDPOINT" ]; then
  echo "Uploading static assets to Cloudflare R2..."
  
  # Configure AWS CLI for Cloudflare R2
  export AWS_ACCESS_KEY_ID="$R2_ACCESS_KEY_ID"
  export AWS_SECRET_ACCESS_KEY="$R2_SECRET_ACCESS_KEY"
  export AWS_ENDPOINT_URL="$R2_S3_ENDPOINT"
  
  # Upload build directory to R2
  if [ -d "$REPO_ROOT/public/build" ]; then
    echo "Uploading build assets..."
    aws s3 sync "$REPO_ROOT/public/build" "s3://$R2_BUCKET_NAME/build" --endpoint-url "$R2_S3_ENDPOINT"
    
    # Set proper content types for CSS files
    echo "Setting proper content types for CSS files..."
    find "$REPO_ROOT/public/build" -name "*.css" | while read -r css_file; do
      relative_path=${css_file#"$REPO_ROOT/public/"}
      aws s3 cp "s3://$R2_BUCKET_NAME/$relative_path" "s3://$R2_BUCKET_NAME/$relative_path" \
        --endpoint-url "$R2_S3_ENDPOINT" \
        --content-type "text/css" \
        --metadata-directive REPLACE
    done
    
    echo "Static assets uploaded to Cloudflare R2."
  else
    echo "No build directory found at $REPO_ROOT/public/build. Skipping asset upload."
  fi
else
  echo "Skipping CDN upload - R2 credentials not configured."
  echo "To enable CDN uploads, add the following to your .env.deploy file:"
  echo "R2_BUCKET_NAME=your_bucket_name"
  echo "R2_ACCESS_KEY_ID=your_access_key"
  echo "R2_SECRET_ACCESS_KEY=your_secret_key"
  echo "R2_S3_ENDPOINT=https://xxxx.r2.cloudflarestorage.com"
fi
end_step

# 6. Generate .env file for the server
step "Generating .env file for server"
ENV_FILE="$BUILD_DIR/.env"

# Start with .env.example as base if it exists
if [ -f "$REPO_ROOT/.env.example" ]; then
  cp "$REPO_ROOT/.env.example" "$ENV_FILE"
else
  touch "$ENV_FILE"
fi

# Merge with .env.appprod if it exists
if [ -f "$SCRIPT_DIR/.env.appprod" ]; then
  while IFS= read -r line; do
    if [[ $line == *=* ]] && [[ ! $line =~ ^\s*# ]]; then
      key=$(echo "$line" | cut -d= -f1)
      # Replace or append the line
      if grep -q "^$key=" "$ENV_FILE"; then
        sed -i.bak "s|^$key=.*|$line|" "$ENV_FILE" && rm "$ENV_FILE.bak"
      else
        echo "$line" >> "$ENV_FILE"
      fi
    fi
  done < "$SCRIPT_DIR/.env.appprod"
fi

# Merge with .env.deploy if it exists
if [ -f "$SCRIPT_DIR/.env.deploy" ]; then
  while IFS= read -r line; do
    if [[ $line == *=* ]] && [[ ! $line =~ ^\s*# ]]; then
      key=$(echo "$line" | cut -d= -f1)
      # Only include app-related variables, not deployment config
      if [[ ! $key =~ ^(SSH_|REMOTE_|APP_DIR|GIT_) ]]; then
        # Replace or append the line
        if grep -q "^$key=" "$ENV_FILE"; then
          sed -i.bak "s|^$key=.*|$line|" "$ENV_FILE" && rm "$ENV_FILE.bak"
        else
          echo "$line" >> "$ENV_FILE"
        fi
      fi
    fi
  done < "$SCRIPT_DIR/.env.deploy"
fi

# Add any additional environment variables from command line
for var in "${ADDITIONAL_ENV_VARS[@]}"; do
  key=$(echo "$var" | cut -d= -f1)
  # Replace or append the variable
  if grep -q "^$key=" "$ENV_FILE"; then
    sed -i.bak "s|^$key=.*|$var|" "$ENV_FILE" && rm "$ENV_FILE.bak"
  else
    echo "$var" >> "$ENV_FILE"
  fi
done

# Ensure APP_ENV is set to production
if ! grep -q "^APP_ENV=" "$ENV_FILE"; then
  echo "APP_ENV=production" >> "$ENV_FILE"
else
  sed -i.bak "s|^APP_ENV=.*|APP_ENV=production|" "$ENV_FILE" && rm "$ENV_FILE.bak"
fi

# Ensure APP_DEBUG is set to false for security
if ! grep -q "^APP_DEBUG=" "$ENV_FILE"; then
  echo "APP_DEBUG=false" >> "$ENV_FILE"
else
  sed -i.bak "s|^APP_DEBUG=.*|APP_DEBUG=false|" "$ENV_FILE" && rm "$ENV_FILE.bak"
fi

# Set APP_URL if DOMAIN is provided
if [ -n "$DOMAIN" ]; then
  if ! grep -q "^APP_URL=" "$ENV_FILE"; then
    echo "APP_URL=https://$DOMAIN" >> "$ENV_FILE"
  else
    sed -i.bak "s|^APP_URL=.*|APP_URL=https://$DOMAIN|" "$ENV_FILE" && rm "$ENV_FILE.bak"
  fi
fi

echo ".env file generated at $ENV_FILE"
end_step

# 7. Generate deployment script for the server
step "Generating deployment script for server"
DEPLOY_SCRIPT="$BUILD_DIR/server-deploy.sh"

cat > "$DEPLOY_SCRIPT" << 'EOL'
#!/bin/bash
set -e
set -o pipefail

# This script is generated automatically by the deployment process
# It will be executed on the server to complete the deployment

# Get the directory of this script
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
APP_DIR="$(dirname "$SCRIPT_DIR")"

# Load environment variables
if [ -f "$APP_DIR/.env" ]; then
  set -a
  source "$APP_DIR/.env"
  set +a
fi

# Function to log with timestamp
log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

# Function to handle failures
fail() {
  echo "❌ ERROR: $1"
  exit 1
}

# Run Laravel commands
log "Running composer install..."
cd "$APP_DIR"
composer install --no-dev --optimize-autoloader --no-interaction

log "Running database migrations..."
php artisan migrate --force

log "Optimizing Laravel..."
php artisan optimize
php artisan config:cache
php artisan route:cache
php artisan view:cache

log "Creating storage symlink..."
php artisan storage:link

log "Setting proper permissions..."
find storage bootstrap/cache -type d -exec chmod 775 {} \;
find storage bootstrap/cache -type f -exec chmod 664 {} \;
chown -R www-data:www-data storage bootstrap/cache

log "Deployment completed successfully!"
EOL

chmod +x "$DEPLOY_SCRIPT"
echo "Server deployment script generated at $DEPLOY_SCRIPT"
end_step

# 8. Generate health check file
step "Generating health check file"
HEALTH_FILE="$BUILD_DIR/health.txt"
echo "OK - $(date)" > "$HEALTH_FILE"
echo "Health check file generated at $HEALTH_FILE"
end_step

# 9. Clone or update the git repository on the server
step "Cloning or updating the git repository on the server"
# Clean up the local git repository to avoid pushing unwanted files
echo "Cleaning git repository..."
git clean -xdf -e node_modules -e vendor -e .env -e storage -e deploy

# Stash any local changes
echo "Stashing any local changes..."
git stash

# Make sure we're on the correct branch
echo "Your branch is up to date with 'origin/$GIT_BRANCH'."
git checkout "$GIT_BRANCH"

# Pull the latest changes
echo "From $GIT_REPO"
echo " * branch            $GIT_BRANCH -> FETCH_HEAD"
git pull origin "$GIT_BRANCH"
end_step

# 10. Ensure host storage directory structure and permissions
step "Ensuring host storage directory structure and permissions"
# Create necessary directories on the server
execute_ssh "mkdir -p $APP_DIR/storage/app/public $APP_DIR/storage/framework/cache $APP_DIR/storage/framework/sessions $APP_DIR/storage/framework/views $APP_DIR/storage/logs $APP_DIR/bootstrap/cache"

# Set proper permissions
execute_ssh "chmod -R 775 $APP_DIR/storage $APP_DIR/bootstrap/cache"
end_step

# 11. Upload remaining public files to server
step "Uploading remaining public files to server"
# Create a tar of the public directory excluding build directory if it's being served from CDN
if [ -n "$R2_BUCKET_NAME" ]; then
  echo "Creating tar of public directory excluding build directory..."
  tar -czf "$BUILD_DIR/public.tar.gz" -C "$REPO_ROOT" --exclude="public/build" public
else
  echo "Creating tar of public directory..."
  tar -czf "$BUILD_DIR/public.tar.gz" -C "$REPO_ROOT" public
fi

# Upload the tar to the server
scp -i "$SSH_KEY" "$BUILD_DIR/public.tar.gz" "$SSH_USER@$SSH_HOST:$APP_DIR/"

# Extract the tar on the server
execute_ssh "cd $APP_DIR && tar -xzf public.tar.gz && rm public.tar.gz"

echo "Remaining public files uploaded to server."
end_step

# 12. Setting up docker environment on server & starting containers
step "Setting up docker environment on server & starting containers"
# Create necessary directories on the server
execute_ssh "mkdir -p $APP_DIR/deploy $APP_DIR/docker"

# Copy deployment scripts to server
log "Copying deployment script to the server..."
ssh -i "$SSH_KEY" "$SSH_USER@$SSH_HOST" "mkdir -p $APP_DIR/deploy"
scp -i "$SSH_KEY" "$SCRIPT_DIR/blue-green-ssl-deploy.sh" "$SSH_USER@$SSH_HOST:$APP_DIR/deploy/"
scp -i "$SSH_KEY" "$SCRIPT_DIR/docker-compose-template.yml" "$SSH_USER@$SSH_HOST:$APP_DIR/deploy/"
ssh -i "$SSH_KEY" "$SSH_USER@$SSH_HOST" "chmod +x $APP_DIR/deploy/blue-green-ssl-deploy.sh"

# Copy environment files to the server
log "Copying environment files to the server..."
scp -i "$SSH_KEY" "$ENV_FILE" "$SSH_USER@$SSH_HOST:$APP_DIR/.env"

# Copy Docker configuration files if they exist
if [ -d "$REPO_ROOT/docker" ]; then
  log "Copying Docker configuration files..."
  scp -i "$SSH_KEY" -r "$REPO_ROOT/docker" "$SSH_USER@$SSH_HOST:$APP_DIR/"
fi
end_step

# 13. Copying .env file
step "Copying .env file"
# Already done in step 12
end_step

# 14. Ensuring SSL certificate and key exist on server
step "Ensuring SSL certificate and key exist on server"
# SSL certificates will be handled by Let's Encrypt via Traefik
end_step

# 15. Ensuring Laravel cache and storage directories exist and are writable
step "Ensuring Laravel cache and storage directories exist and are writable"
# Already done in step 10
end_step

# 16. Executing deployment commands
step "Executing deployment commands"
# Execute the blue-green deployment script on the server
log "Using blue-green deployment strategy with Let's Encrypt SSL"
log "Creating necessary directories on the server..."
execute_ssh "mkdir -p $APP_DIR/docker"

log "Copying deployment script to the server..."
scp -i "$SSH_KEY" "$SCRIPT_DIR/blue-green-ssl-deploy.sh" "$SSH_USER@$SSH_HOST:$APP_DIR/deploy/"
execute_ssh "chmod +x $APP_DIR/deploy/blue-green-ssl-deploy.sh"

log "Copying environment files to the server..."
scp -i "$SSH_KEY" "$ENV_FILE" "$SSH_USER@$SSH_HOST:$APP_DIR/.env"

log "Copying Docker configuration files..."
if [ -d "$REPO_ROOT/docker" ]; then
  scp -i "$SSH_KEY" -r "$REPO_ROOT/docker" "$SSH_USER@$SSH_HOST:$APP_DIR/"
fi

log "Executing blue-green deployment script on the server..."
DOMAIN=${DOMAIN:-"harun.dev"}
EMAIL=${EMAIL:-"contact@harun.dev"}
execute_ssh "cd $APP_DIR && ./deploy/blue-green-ssl-deploy.sh --domain=$DOMAIN --email=$EMAIL"
end_step

# 17. Verify deployment
step "Verifying deployment"
# Check if the site is accessible
if [ -n "$DOMAIN" ]; then
  echo "Checking if site is accessible at https://$DOMAIN..."
  if curl -s -o /dev/null -w "%{http_code}" "https://$DOMAIN"; then
    echo "✅ Site is accessible at https://$DOMAIN"
  else
    echo "⚠️ Site may not be accessible yet. This could be due to DNS propagation or other issues."
    echo "Please check manually in a few minutes."
  fi
else
  echo "No domain specified, skipping site accessibility check."
fi
end_step

# 18. Clean up
step "Cleaning up"
echo "Cleaning up local build directory..."
rm -rf "$BUILD_DIR"
end_step

# 19. Purge CDN Cache (Cloudflare)
step "Purging CDN Cache (Cloudflare)"
if [ -z "$CLOUDFLARE_ZONE_ID" ] || [ -z "$CLOUDFLARE_API_TOKEN" ]; then
  echo "Skipping Cloudflare CDN purge - missing CLOUDFLARE_ZONE_ID or CLOUDFLARE_API_TOKEN"
  echo "To enable Cloudflare cache purging, add the following to your .env.deploy file:"
  echo "CLOUDFLARE_API_TOKEN=your_api_token"
  echo "CLOUDFLARE_ZONE_ID=your_zone_id"
else
  echo "Attempting to purge Cloudflare cache for zone ID $CLOUDFLARE_ZONE_ID"
  if [ -n "$CLOUDFLARE_API_TOKEN" ]; then
    echo "Using API Token authentication method..."
    RESULT=$(curl -s -X POST \
      "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
      -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
      -H "Content-Type: application/json" \
      --data '{"purge_everything":true}')

    # Parse JSON properly to check for success
    SUCCESS=$(echo "$RESULT" | grep -o '"success":[^,}]*' | cut -d ':' -f2 | tr -d ' ')
    if [[ "$SUCCESS" == "true" ]]; then
      echo "Cloudflare cache purged successfully!"
    else
      echo "Failed to purge Cloudflare cache. Response: $RESULT"
    fi
  elif [ -n "$CLOUDFLARE_EMAIL" ] && [ -n "$CLOUDFLARE_API_KEY" ]; then
    echo "Using API Key authentication method..."
    RESULT=$(curl -s -X POST \
      "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
      -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
      -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
      -H "Content-Type: application/json" \
      --data '{"purge_everything":true}')

    # Parse JSON properly to check for success
    SUCCESS=$(echo "$RESULT" | grep -o '"success":[^,}]*' | cut -d ':' -f2 | tr -d ' ')
    if [[ "$SUCCESS" == "true" ]]; then
      echo "Cloudflare cache purged successfully!"
    else
      echo "Failed to purge Cloudflare cache. Response: $RESULT"
    fi
  else
    echo "Missing Cloudflare authentication credentials. Please provide either API Token or Email + API Key."
  fi
fi

# Print total time and summary
print_total_time
